[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"
authors = ["Mats Kindahl <mats.kindahl@gmail.com>"]

[dependencies]
regex = "~1.7"
num = "0.3.1"
itertools = "0.8"
lazy_static = "1.4.0"
